### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by humancalico** [ryzokuken/sophosd#1]
Update README file and add documentation

**Comment by ryzokuken** [comment]
@akshat2654 thanks for the issue! Would you like to make a PR yourself? Feel free to ask for help if you do.

**Comment by akshat2654** [comment]
@ryzokuken While running sophosd it is giving me this error. Can you tell me more about this issue and help me resolve it.
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /usr/src/rustc-1.36.0/src/libcore/slice/mod.rs:2695:10
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_main
  16: <unknown>

```

**Comment by ryzokuken** [comment]
I'm pretty sure you ran it without arguments.

**Comment by akshat2654** [comment]
@ryzokuken Please assign the issue to me. I'll try to contribute to the documentation by tomorrow at the latest.

**Comment by ryzokuken** [comment]
@akshat2654 done!

**Comment by akshat2654** [comment]
@ryzokuken Should the README file have anything apart from these things:

1. Description
2. Installing
3. Usage
4. Common issues

Also should I upload the binary Debian package as it is more easier for users to use it than compiling from the source code. If yes where and how should I upload it?

**Comment by ryzokuken** [comment]
@akshat2654 once I have a decent chunk of functionality, I'll build the binaries and upload them on the releases page. sophosd never had a release so I never uploaded any binaries.
